version: "3.2"

networks:
  frontend:
  backend:

services:
  catalog:
    build:
      context: ./src/Services/Catalog/O2.Catalog.API
      dockerfile: Dockerfile
    image: o2bionics/o2-catalog.api
    environment:
      - DatabaseServer=mssqlserver
      - DatabaseName=CatalogDb
      - DatabaseUser=sa
      - DatabasePassword=_DEVELOPER_RACE_

    container_name: catalogapi
    ports:
      - "5000:80"
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver


  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    ports: 
      - "1445:1433"
    
    container_name: mssqlservercontainer
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=_DEVELOPER_RACE_
    networks: 
      - backend

